---

- name: Prepare controller for execution
  hosts: localhost
  tags: always
  tasks:
    - name: Configure for standalone role testing
      ansible.builtin.include_role:
        name: syndr.molecule.prepare_controller
      vars:
        prepare_controller_project_type: role

- name: Prepare target host for execution
  hosts: molecule
  tags: always
  tasks:
    ##
    # Creating an admin service account for Molecule/Ansible to use for testing
    #
    #   - If you run Ansible as a service account (you should) on your hosts and
    #     not as root, it is wise to also test as a non-root user!
    #
    #   - To use this account, add the following to any plays targeting test
    #     infrastructure (such as in converge.yml):
    #
    #         vars:
    #           ansible_user: molecule_runner
    ##

    - name: Create ansible service account
      vars:
        molecule_user: molecule_runner
      block:
        - name: Create ansible group
          ansible.builtin.group:
            name: "{{ molecule_user }}"

        - name: Create ansible user
          ansible.builtin.user:
            name: "{{ molecule_user }}"
            group: "{{ molecule_user }}"

        - name: Sudoers.d directory exists
          ansible.builtin.file:
            path: /etc/sudoers.d
            state: directory
            owner: root
            group: root
            mode: 0751

        - name: Ansible user has sudo
          ansible.builtin.copy:
            content: |
              {{ molecule_user }}  ALL=(ALL)  NOPASSWD: ALL
            dest: /etc/sudoers.d/ansible
            owner: root
            group: root
            mode: 0600

    - name: "Save vars to host (IE: generated test credentials, etc.)"
      become: true
      block:
        - name: Ansible facts directory exists
          ansible.builtin.file:
            path: /etc/ansible/facts.d
            state: directory
            owner: root
            group: root
            mode: 0755

        - name: Persistent data saved to local Ansible facts
          ansible.builtin.copy:
            dest: /etc/ansible/facts.d/molecule.fact
            content: "{{ {'test_prepare_fact': 'this is an example!'} | to_json }}"
            owner: root
            group: root
            mode: 0644

    - name: Add your host preparation tasks here!
      ansible.builtin.debug:
        msg: "IE: adding system users, installing required packages, etc."

